FROM python:3.11-slim

WORKDIR /app

COPY notification-service /app/notification-service

RUN pip install --no-cache-dir -r notification-service/requirements.txt

COPY shared /app/shared
RUN pip install --no-cache-dir -e /app/shared

WORKDIR /app/notification-service

EXPOSE 5002

CMD ["python", "main.py"]



