FROM python:3.11-slim

WORKDIR /app

COPY order-service/requirements.txt ./requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY shared /app/shared
RUN pip install --no-cache-dir -e /app/shared

RUN rm -rf ./shared ./requirements


EXPOSE 8002

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]

